apiVersion: v1
kind: Service
metadata:
  name: parent-frontend
spec:
  ports:
  #- port: 3000
  - port: 80
    targetPort: cratefront-port
    nodePort: 31000
  selector:
    app: parent-frontend
  type: NodePort
  #clusterIP: 100.68.66.215

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: parent-frontend
  labels:
    app: parent-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parent-frontend
  template:
    metadata:
      labels:
        app: parent-frontend
    spec:
      containers:
      - name: parent-frontend
        #image: dutta249/crate:frontend14.0
        image: "{{ .Values.image.parentimage }}:{{ .Values.image.tag }}"
        volumeMounts:
        - name: env-configmap
          #mountPath: /app/.env
          mountPath: .env
          subPath: .env
        ports:
        - name: cratefront-port
          #containerPort: 3000
          containerPort: 80
#      initContainers:
#      - name: init-mydb
#        image: busybox
#        command: ['sh', '-c', 'until nslookup backend; do echo waiting for mydb; sleep 2; done;']
      imagePullSecrets:
      - name: my-dockerhub-creds
      volumes:
        - name: env-configmap
          configMap:
            name: env-configmap
